### PR TITLE
ErrorCode1

### PR DESCRIPTION
**Pull request by Priyadharshini-B-23**
Yeah Kathir ,I resolve the bugs .Could you review my code again if there is any other bugs are there?

### CODE REVIEW

**Comment by KATHIRVELSIVA** [comment]
Priya error for the previous code is resolved but there was an missing of the parantheses in the line 37. Could you please resolve it .

**Comment by Priyadharshini-B-23** [comment]
Okay Kathir.
I clear the bugs.Could you please check it?

**Comment by KATHIRVELSIVA** [comment]
Ok good Priya Thanks for resolving the error.

**Comment by Priyadharshini-B-23** [comment]
> Ok good Priya Thanks for resolving the error.

Thank you Kathir for your kind responces and reviewing my code

**Pull request merged**
